// <auto-generated />
namespace _6.MyModelMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Dataanotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dataanotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201803150550390_Dataanotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
